namespace Domain.GameLogs.Entities;

public enum Platform
{
    Pc,
    PlayStation,
    PlayStation2,
    PlayStation3,
    PlayStation4,
    PlayStation5,
    PlaystationPortable,
    PlaystationVita,
    Xbox,
    Xbox360,
    XboxOne,
    XboxSeries,
    GameBoy,
    GameBoyAdvance,
    NintendoDs,
    Nintendo3ds,
    NintendoEntertainmentSystem,
    SuperNintendo,
    Nintendo64,
    GameCube,
    NintendoWii,
    NintendoWiiU,
    NintendoSwitch,
    Android,
    Ios,
}
