# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  web-api:
    build:
      context: "C:\\Users\\Nilton\\Desktop\\GameLog"
      dockerfile: "src/Web.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "webapi:dev"
    ports:
    - "127.0.0.1:57002:57100"
    - "127.0.0.1:57202:57300"
    volumes:
    - "C:\\Users\\Nilton\\AppData\\Roaming\\Microsoft\\UserSecrets:/home/app/.microsoft/usersecrets"
    - "C:\\Users\\Nilton\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Nilton\\Desktop\\GameLog\\src\\Web.Api:/app:rw"
    - "C:\\Users\\Nilton\\Desktop\\GameLog:/src:rw"
    - "C:\\Users\\Nilton\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1.2\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.1.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Nilton\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_10_02_09_59_43:/var/opt/rider-debugger:rw"
    working_dir: "/app"
